version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - .env
